### ISSUE TITLE
Docker compose usage

### ISSUE THREAD

**Issue by DanielBaulig** [vfreex/mdns-reflector#15]
Might be worth adding to the documentation:

```
services:
  mdns-reflector:
    image: yuxzhu/mdns-reflector:latest
    command: mdns-reflector -fn eth0 br-${COMPOSE_PROJECT_NAME}
    network_mode: host
    restart: always
  some-service-requiring-mdns:
    // ...
    networks:
      - default
networks:
  default:
    driver: bridge
    driver_opts: 
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME}
```
